pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                echo '1开始拉取代码.....'
                git  branch: 'prod', credentialsId: 'GitHub', url: 'https://github.com/Mrtest-test/simple-java-maven-app.git'
            }
        }
        stage('Build') {
            steps {
                echo '2开始执行打包操作.......'
                sh 'D:\\\\\\soft\\\\apache-maven-3.6.3\\\\bin\\\\mvn clean package -U'
            }
        }

        stage('Deploy') {
            steps {
                echo '3测活成功'
            }
        }

        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
